import { Recommendation } from './types';

export const RECOMMENDATIONS: Recommendation[] = [
  {
    id: '1',
    name: 'Cursor',
    url: 'https://cursor.sh',
    category: '开发工具',
    description: '基于 AI 的代码编辑器，内置了强大的代码补全和重构功能。',
    reason: '目前最强大的 AI 辅助编程工具，能够极大地提升开发效率，理解上下文能力极强。',
    howToUse: '下载安装后，可以使用 Cmd+K 进行代码生成，Cmd+L 进行对话式编程。它能自动索引你的项目文件。',
    tags: ['AI', 'IDE', '效率'],
    localIcon: 'cursor.png',
  },
  {
    id: '2',
    name: 'V0.dev',
    url: 'https://v0.dev',
    category: '开发工具',
    description: 'Vercel 推出的 AI 生成 UI 组件的工具，支持 React 和 Tailwind CSS。',
    reason: '通过自然语言描述即可生成精美的 UI 组件，极大缩短了前端开发时间。',
    howToUse: '在输入框中描述你想要的 UI 界面，AI 会生成多个版本供你选择，点击即可复制代码。',
    tags: ['AI', 'Frontend', 'UI'],
    localIcon: 'vo.png',
  },
  {
    id: '3',
    name: 'Raycast',
    url: 'https://www.raycast.com',
    category: '效率提升',
    description: 'macOS 上的全能效率工具，可以替代 Spotlight。',
    reason: '插件生态极其丰富，支持剪贴板管理、窗口管理、计算器、翻译等几乎所有常用功能。',
    howToUse: '安装后设置快捷键启动，通过输入关键词搜索并执行各种操作或插件。',
    tags: ['Mac', 'Efficiency', 'Tool'],
    localIcon: 'raycast.png',
  },
  {
    id: '4',
    name: 'Excalidraw',
    url: 'https://excalidraw.com',
    category: '设计资源',
    description: '手绘风格的在线白板工具，非常适合绘制架构图和草图。',
    reason: '极简、开源、免费，手绘风格让图表看起来更亲切且易于理解。',
    howToUse: '直接在网页上绘图，支持导出为图片或 SVG，也可以多人实时协作。',
    tags: ['Design', 'Whiteboard', 'OpenSource'],
    localIcon: 'excalidraw.png',
  },
  {
    id: '5',
    name: 'Shadcn UI',
    url: 'https://ui.shadcn.com',
    category: '开发工具',
    description: '精美的可复制粘贴的 UI 组件库。',
    reason: '不是一个传统的 NPM 包，而是直接将代码复制到你的项目中，方便自定义和控制。',
    howToUse: '根据文档使用 CLI 工具添加组件，或者手动复制代码到你的 components 文件夹。',
    tags: ['React', 'Tailwind', 'UI'],
    localIcon: 'shadcn.png',
  },
  {
    id: '6',
    name: 'Perplexity AI',
    url: 'https://www.perplexity.ai',
    category: 'AI工具',
    description: 'AI 驱动的搜索引擎，提供准确的引用和实时信息内容。',
    reason: '比传统的搜索引擎更直接，比单纯的 LLM 更准确，因为它会实时搜索并给出来源。',
    howToUse: '像使用 Google 一样提问，它会总结搜索结果并列出参考链接。',
    tags: ['AI', 'Search', 'Research'],
    localIcon: 'perplexity.png',
  },
  {
    id: '7',
    name: 'AI Studio',
    url: 'https://aistudio.google.com/',
    category: 'AI工具',
    description: 'Google 提供的开发者平台，用于快速原型设计和测试 Gemini 模型。',
    reason: '它是目前最快、最直接体验 Google 最新 AI 模型（如 Gemini 1.5 Pro/Flash）的地方，支持长上下文。',
    howToUse: '登录后选择模型，输入提示词进行测试，还可以直接生成 API Key 用于开发。',
    tags: ['Google', 'Gemini', 'AI'],
    localIcon: 'aistudio.jpeg',
  },
  {
    id: '8',
    name: 'Google Stitch',
    url: 'https://stitch.withgoogle.com/',
    category: '其他',
    description: 'Google 的一个实验性项目，旨在通过简单的交互方式连接不同的创意和想法。',
    reason: '展示了 Google 在交互设计和创意表达方面的最新探索。',
    howToUse: '访问网站，按照指引进行交互式体验。',
    tags: ['Experiment', 'Google', 'Creative'],
    localIcon: 'stitch.png',
  },
  {
    id: '9',
    name: 'Flow',
    url: 'https://labs.google/flow/about',
    category: 'AI工具',
    description: '一款用ai技术生成图片和视频的网站。',
    reason: 'Google Labs 推出的最新 AI 创意工具，展示了 AI 在视觉内容生成方面的巨大潜力。',
    howToUse: '访问网站了解 Flow 的功能，并根据指引体验 AI 生成图片和视频。',
    tags: ['AI', 'Video', 'Image'],
  },
  {
    id: '10',
    name: 'Longcut',
    url: 'https://www.longcut.ai/',
    category: 'AI工具',
    description: 'AI 驱动的视频剪辑工具，能够自动将长视频切片为适合社交媒体的短视频。',
    reason: '极大地简化了短视频内容的创作流程，适合博主和营销人员。',
    howToUse: '上传长视频，AI 会自动识别精彩片段并生成短视频，支持一键导出。',
    tags: ['Video', 'AI', 'SocialMedia'],
    localIcon: 'longcut.png',
  },
  {
    id: '11',
    name: 'NotebookLM',
    url: 'https://notebooklm.google.com/',
    category: 'AI工具',
    description: 'Google 推出的 AI 笔记本，可以根据你上传的文档进行总结、回答问题和生成创意。',
    reason: '它是目前最强的文档理解工具之一，能够基于你的私有数据提供精准的回答。',
    howToUse: '创建笔记本，上传 PDF、文本或网页链接，然后与 AI 进行对话或生成摘要。',
    tags: ['Google', 'Notebook', 'Research'],
    localIcon: 'notebook-logo.svg',
  },
  {
    id: '12',
    name: 'Class Central',
    url: 'https://www.classcentral.com/',
    category: '学习资源',
    description: '全球最大的在线课程搜索引擎，汇集了各大平台的优质课程。',
    reason: '找课神器，提供真实的课程评价和排名，帮你找到最优质的学习资源。',
    howToUse: '在搜索框输入你想学的技能，查看课程评分、难度和用户反馈。',
    tags: ['Education', 'MOOC', 'Learning'],
    localIcon: 'classcentral.png',
  },
  {
    id: '13',
    name: 'Granola',
    url: 'https://www.granola.ai/',
    category: '效率提升',
    description: 'AI 会议助手，能够自动记录会议内容并生成结构化的笔记和待办事项。',
    reason: '它不仅是录音，更重要的是它能理解会议背景并生成高质量的总结，让你专注于沟通。',
    howToUse: '在会议开始时开启 Granola，它会静默记录并自动生成会议纪要。',
    tags: ['Meeting', 'AI', 'Productivity'],
    localIcon: 'granola.png',
  },
  {
    id: '14',
    name: 'Tosea',
    url: 'https://tosea.ai/',
    category: 'AI工具',
    description: '一个专注于 AI 搜索和内容生成的平台，旨在提供更高效的信息获取体验。',
    reason: '界面简洁，搜索结果精准，是 Perplexity 的有力竞争者。',
    howToUse: '输入问题，它会实时搜索全网并总结出答案。',
    tags: ['Search', 'AI', 'Intelligence'],
    localIcon: 'tosea.png',
  },
  {
    id: '15',
    name: 'Pencil',
    url: 'https://www.pencil.dev/',
    category: '设计资源',
    description: 'AI 驱动的广告创意生成平台，帮助品牌快速生成高质量的视频和图片广告。',
    reason: '结合了数据分析和创意生成，能够预测广告效果并不断优化。',
    howToUse: '输入品牌信息和目标，AI 会自动生成多种风格的广告素材。',
    tags: ['Design', 'Ads', 'AI'],
    localIcon: 'pencil.png',
  },
  {
    id: '16',
    name: 'PaddleOCR',
    url: 'https://aistudio.baidu.com/paddleocr',
    category: '开发工具',
    description: '百度飞桨推出的开源 OCR 工具库，支持多种语言和场景的文字识别。',
    reason: '中文识别效果极佳，性能强劲，是目前最受欢迎的开源 OCR 项目之一。',
    howToUse: '可以在 AI Studio 上直接体验 Demo，也可以下载源码集成到自己的项目中。',
    tags: ['OCR', 'Baidu', 'AI'],
    localIcon: 'paddleocr.png',
  },
  {
    id: '17',
    name: '考试酷',
    url: 'https://www.examcoo.com/',
    category: '学习资源',
    description: '一个永久免费的公益性在线考试系统，支持各种类型的考试和练习。',
    reason: '资源极其丰富，涵盖了从小学到大学、从职业资格到语言考试的各类题库。',
    howToUse: '注册登录后，可以搜索感兴趣的考试科目进行在线练习或模拟考试。',
    tags: ['Education', 'Exam', 'Learning'],
    localIcon: 'examcoo.png',
  },
  {
    id: '18',
    name: 'MuscleWiki',
    url: 'https://musclewiki.com/',
    category: '其他',
    description: '一个极简的健身百科全书，通过点击人体肌肉图即可查看对应的锻炼动作。',
    reason: '非常直观，没有任何多余的干扰，每个动作都配有清晰的 GIF 演示和文字说明。',
    howToUse: '在首页的人体模型上点击你想锻炼的肌肉群，系统会自动列出相关的训练动作。',
    tags: ['Fitness', 'Health', 'Wiki'],
    localIcon: 'musclewiki.png',
  },
  {
    id: '19',
    name: 'Lovart',
    url: 'https://www.lovart.ai/',
    category: '设计资源',
    description: '一个专注于 AI 艺术创作和分享的平台，提供多种风格的生成模型。',
    reason: '社区氛围好，生成的艺术作品质量极高，是寻找 AI 绘画灵感的好去处。',
    howToUse: '输入提示词并选择风格模型，点击生成即可获得独特的 AI 艺术作品。',
    tags: ['AI Art', 'Design', 'Creative'],
    localIcon: 'lovart.png',
  },
  {
    id: '20',
    name: 'Artvee',
    url: 'https://artvee.com/',
    category: '设计资源',
    description: '一个提供公共领域（Public Domain）艺术作品下载的网站，涵盖了古典名画和插图。',
    reason: '所有作品均可免费下载并用于商业用途，是寻找高质量古典艺术素材的宝库。',
    howToUse: '通过分类或关键词搜索艺术家和作品，选择合适的分辨率进行下载。',
    tags: ['Art', 'Design', 'Classic'],
    localIcon: 'artvee.png',
  },
  {
    id: '21',
    name: 'WaytoAGI',
    url: 'https://www.waytoagi.com/',
    category: '学习资源',
    description: '国内最全面的 AI 知识库和导航站，致力于普及 AI 技术和应用。',
    reason: '内容更新极快，整理了大量的 AI 教程、工具和行业动态，是入门 AI 的最佳起点。',
    howToUse: '浏览首页的推荐内容，或者通过分类导航查找特定的 AI 学习资源。',
    tags: ['AI', 'Knowledge', 'Learning'],
    localIcon: 'waytoagi.png',
  },
  {
    id: '22',
    name: 'Dev.to',
    url: 'https://dev.to/',
    category: '开发工具',
    description: '一个全球性的开发者社区，程序员们在这里分享知识、经验和项目。',
    reason: '内容质量高，互动性强，是了解最新技术趋势和解决编程问题的绝佳平台。',
    howToUse: '注册账号后可以关注感兴趣的标签，阅读文章或发表自己的技术见解。',
    tags: ['Developer', 'Community', 'Programming'],
    localIcon: 'dev-to.png',
  },
  {
    id: '23',
    name: '识典古籍',
    url: 'https://www.shidianguji.com/',
    category: '学习资源',
    description: '由字节跳动与北京大学联合推出的古籍数字化平台，提供海量古籍的在线阅读和搜索。',
    reason: '界面极其精美，支持繁简转换和全文检索，让古籍阅读变得前所未有的轻松。',
    howToUse: '在搜索框输入书名或关键词，即可在线阅读高清数字化的古籍文献。',
    tags: ['History', 'Culture', 'Reading'],
    localIcon: 'shidianguji.png',
  }
];

export const CATEGORIES: string[] = ['全部', 'AI工具', '开发工具', '设计资源', '效率提升', '学习资源', '其他'];
